package io.github.PacMan.Game_Objects.Models.Barrier;

public enum Texture_Type {
    // Proste linie
    STRAIGHT_HORIZONTAL_UP,
    STRAIGHT_HORIZONTAL_DOWN,
    STRAIGHT_VERTICAL_LEFT,
    STRAIGHT_VERTICAL_RIGHT,

    // Zewnętrzne rogi
    OUTER_ARC_BOTTOM_RIGHT,
    OUTER_ARC_BOTTOM_LEFT,
    OUTER_ARC_TOP_LEFT,
    OUTER_ARC_TOP_RIGHT,

    // Wewnętrzne rogi
    INSIDE_ARC_TOP_RIGHT,
    INSIDE_ARC_TOP_LEFT,
    INSIDE_ARC_BOTTOM_RIGHT,
    INSIDE_ARC_BOTTOM_LEFT,

    // Łączniki granicy mapy z figurą (tylko dla BORDER)
    BORDER_HORIZONTAL_LEFT_BOTTOM_CONNECTOR,
    BORDER_HORIZONTAL_LEFT_TOP_CONNECTOR,
    BORDER_HORIZONTAL_RIGHT_TOP_CONNECTOR,
    BORDER_HORIZONTAL_RIGHT_BOTTOM_CONNECTOR,

    BORDER_VERTICAL_LEFT_BOTTOM_CONNECTOR,
    BORDER_VERTICAL_LEFT_TOP_CONNECTOR,
    BORDER_VERTICAL_RIGHT_TOP_CONNECTOR,
    BORDER_VERTICAL_RIGHT_BOTTOM_CONNECTOR,

    // Proste pojedyńcze linie dla BORDER
    BORDER_STRAIGHT_SINGLELINE_HORIZONTAL_UP,
    BORDER_STRAIGHT_SINGLELINE_HORIZONTAL_DOWN,
    BORDER_STRAIGHT_SINGLELINE_VERTICAL_LEFT,
    BORDER_STRAIGHT_SINGLELINE_VERTICAL_RIGHT,

    DEFAULT,
    NONE
}
